dbservers:
    hosts:
      azure-db-server:
        ansible_host: azure-database

appservers:
     hosts:
      azure-app-server:
        ansible_host: azure-backend
      azure-frontend-server:
        ansible_host: azure-frontend
      azure-docker-server:
        ansible_host: azure-docker-3
        
